### ISSUE TITLE
is there a tutorial available that shows how to use this package?

### ISSUE THREAD

**Issue by ahmeddeladly** [agricolab/pyARtACS#1]
Hello,

Is there a way to know how to use this package? 

Thanks in advance.

Best,
Ahmed

**Comment by agricolab** [comment]
Besides the examples in the readme?

**Comment by aeladly91** [comment]
Hello Robert,

Yes, please. If there is a more elaborate one? Like one showing how to use this package on simulated data?

For example, does the artifacted data in the line below have to be a 1D array?

filtered_data = filter_2d(artifacted_data, freq=20, fs=1000, kernel:ndarray)

Thanks in advance.

Best,
Ahmed

**Comment by agricolab** [comment]
Thanks for your interest. 

IIRC filter_2d has been removed a while ago. You might want to stick to filter_1d.

I'll update the docs and add some more examples.

**Comment by aeladly91** [comment]
Thanks Robert for your reply and code.

**Comment by agricolab** [comment]
FInd the revised docs here https://github.com/agricolab/pyARtACS/releases/download/v0.1/documentation.pdf
Readthedocs is giving me problems right now, and i don't have the time to bugfix rtd so no webpage right now... sry

**Comment by ahmeddeladly** [comment]
Wow! Thanks Rob :)
